project_id = ""

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.ai-triage]
verify_jwt = false
